name: CI | Unit Tests

on:
  push:
    branches-ignore:
      - main-ci
      - release

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_tests:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.12, 3.11.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run Tests
        run: pytest --cov-config=.coveragerc --timeout=120 --timeout_method=thread --cov=runpod --cov-report=xml --cov-report=term-missing --cov-fail-under=100 -W error -p no:cacheprovider -p no:unraisableexception
